"""Charts and the written findings, generated from query results so numbers never drift from the data."""
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

PAPER, INK, GREY, BLUE, YELLOW = "#f5f1e8", "#12162b", "#8a8ea3", "#2b3cff", "#ffd400"


def _style(ax, title):
    ax.set_facecolor(PAPER)
    ax.set_title(title, loc="left", fontsize=12, fontweight="bold", color=INK)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(INK)
    ax.tick_params(colors=INK, labelsize=9)


def charts(results, out_dir):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    monthly = results["q07_monthly_revenue"]
    fig, ax = plt.subplots(figsize=(9, 3.6), facecolor=PAPER)
    peak = monthly["month"].dt.month >= 9
    ax.bar(monthly["month"].dt.strftime("%b %y"), monthly["revenue"] / 1000,
           color=[BLUE if p else GREY for p in peak], width=0.75)
    ax.set_ylabel("Revenue (thousands)", color=INK)
    ax.set_xticks(range(0, len(monthly), 3))
    _style(ax, "Revenue jumps every September to December, in both years")
    fig.tight_layout()
    fig.savefig(out_dir / "monthly_revenue.png", dpi=150, facecolor=PAPER)
    plt.close(fig)

    shift = results["q11_orders_by_shift"]
    fig, ax = plt.subplots(figsize=(6.5, 3), facecolor=PAPER)
    ax.barh(shift["shift"][::-1], shift["orders"][::-1], color=BLUE)
    _style(ax, "Most orders are placed from 5 pm")
    ax.set_xlabel("Orders", color=INK)
    fig.tight_layout()
    fig.savefig(out_dir / "orders_by_shift.png", dpi=150, facecolor=PAPER)
    plt.close(fig)

    cat = results["q03_revenue_profit_by_category"]
    fig, ax = plt.subplots(figsize=(6.5, 3), facecolor=PAPER)
    ax.bar(cat["category"], cat["revenue"] / 1000, color=BLUE, width=0.55)
    ax.set_ylabel("Revenue (thousands)", color=INK)
    _style(ax, "The three categories earn almost the same")
    fig.tight_layout()
    fig.savefig(out_dir / "revenue_by_category.png", dpi=150, facecolor=PAPER)
    plt.close(fig)


def insights(results, quality, path):
    m = results["q07_monthly_revenue"].copy()
    m["peak"] = m["month"].dt.month >= 9
    total = m["revenue"].sum()
    peak_share = m.loc[m["peak"], "revenue"].sum() / total * 100
    peak_avg = m.loc[m["peak"], "revenue"].mean()
    off_avg = m.loc[~m["peak"], "revenue"].mean()
    aov_peak = m.loc[m["peak"], "avg_order_value"].mean()
    aov_off = m.loc[~m["peak"], "avg_order_value"].mean()

    cat = results["q03_revenue_profit_by_category"]
    spread = (cat["revenue"].max() - cat["revenue"].min()) / cat["revenue"].mean() * 100
    shift = results["q11_orders_by_shift"].set_index("shift")
    eve_share = shift.loc["Evening (17 and later)", "orders"] / shift["orders"].sum() * 100
    conc = results["q12_customer_concentration"].iloc[0]
    top = results["q09_top_5_customers"]
    ages = results["q13_revenue_by_age_band"]
    q = dict(zip(quality["check_name"], quality["value"]))

    lines = [
        "# Findings",
        "",
        "Generated by `pipeline.py` from `data/retail_sales.csv`. Re-run the pipeline and every figure below updates.",
        "",
        "## Data quality",
        f"- {q['rows received']} rows received, {q['rows dropped (missing quantity, price, cogs or total)']} dropped for missing money fields, {q['rows kept']} analysed.",
        f"- {q['kept rows with missing age']} kept rows have no age; they are ignored in age analysis only.",
        f"- No duplicate transaction IDs, and total_sale equals quantity x price on every row.",
        "",
        "## What the data says",
        f"1. **Sales are strongly seasonal.** September to December brings {peak_share:.0f}% of two-year revenue "
        f"in 8 of 24 months. An average peak month earns {peak_avg:,.0f} against {off_avg:,.0f} in the other months ({peak_avg / off_avg:.1f}x).",
        f"2. **The peak is driven by order volume, not basket size.** Average order value is {aov_peak:,.0f} in peak months "
        f"and {aov_off:,.0f} otherwise, so stock and staffing matter more than pricing in Q4.",
        f"3. **Categories are nearly interchangeable.** Revenue differs by only {spread:.0f}% between the best and worst category, "
        f"and margins sit within about one point of each other.",
        f"4. **Evenings dominate.** {eve_share:.0f}% of orders are placed from 5 pm.",
        f"5. **Revenue is spread across customers.** The top 10% of customers ({int(conc['customers'] // 10)} of {int(conc['customers'])}) account for "
        f"{conc['top_10pct_revenue_share']}% of revenue, so there is no single-customer dependency.",
        f"6. **Younger buyers spend more per order.** Average order value falls from {ages.iloc[0]['avg_order_value']:,.0f} (18-24) "
        f"to {ages.iloc[-1]['avg_order_value']:,.0f} (55+).",
        "",
        "## Caveats worth stating",
        f"- Customers {', '.join(str(int(c)) for c in top['customer_id'])} place {int(top['orders'].min())} to {int(top['orders'].max())} orders each, far above the average of about "
        f"{q['rows kept'] / conc['customers']:.0f}. Sequential low IDs with heavy activity can indicate placeholder or shared accounts, so customer-level conclusions need checking.",
        "- Equal margins across categories and very regular order values suggest this dataset is synthetic. Treat the patterns as a demonstration of method, not as market evidence.",
        "- Two years of data cannot separate seasonality from one-off promotions.",
        "",
    ]
    Path(path).write_text("\n".join(lines), encoding="utf-8")
